version: '3'
services:
  dds-db:
    image: postgres
    networks:
      - ddsgateway
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: lgbtq_pass
      POSTGRES_DB: lgbtq

  dds-back:
    container_name: dds-back
    image: dds-backend
    networks:
      - ddsgateway
    links:
      - "dds-db:dds-db"
    ports:
      - "8080:8080"

  dds-admin:
    container_name: dds-admin
    image: dds-frontend
    networks:
      - ddsgateway
    ports:
      - "80:80"

networks:
  ddsgateway:
    driver: bridge